### ISSUE TITLE
Create login/auth endpoints for users to login

### ISSUE THREAD

**Issue by GDWR** [AbandonTech/RecipleaseAPI#8]
Create a new controller to allow for login/auth. 
This will need to be able to create and hold auth token, this could be done using JWT? if there is nice support for it.

Blocked by #7

**Comment by fisher60** [comment]
I believe we should use JWT if we are implementing our own auth (storing usernames, passwords, and scope) since it will allow flexibility/scalability in additional scope and not require us to store any tokens. A JWT with an appropriate expiration time should be plenty secure for our app (tokens can last several days? Maybe a default 30 day expiration time?).
